name: Sunburn
main: no.perhenrik.sunburn.SunburnPlugin
version: 1.1.0
author: perhenrik
description: The sun burns all living
commands:
    sunburn:
        description: Shows info
        usage: /sunburn