name: Sunburn
main: no.perhenrik.sunburnplugin.SunburnPlugin
version: 1.0.0
author: perhenrik
description: The sun burns all living
commands:
    sb:
        description: Shows info
        usage: /sb